[build]
  publish = "public/"
  # No build command needed for static site
  command = "echo 'No build needed for static site'"

[[redirects]]
  from = "/"
  to = "/schedule.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/src/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/src/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"